---
title: "Intentional stocking undermines ecological stability"
output:
  pdf_document:
    latex_engine: xelatex
#  word_document:
#    reference_docx: word_format.docx
csl: nature.csl
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding, output_dir = "document_output")
      })
bibliography: reference.bib
fontsize: 11pt
header-includes:
  - \usepackage{lineno}
  - \linenumbers
---

```{r setup, include=FALSE}

# setup
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse)
op <- function(x, d = 2) sprintf(paste0("%1.", d, "f"), x) 

# theory
load(here::here("result/result_ricker.RData"))

n_sim <- sim_result %>% 
  mutate(n_sim = n_warmup + n_burnin + n_timestep) %>% 
  pull(n_sim) %>% 
  unique()

param_set <- sim_result %>% 
  distinct(n_species,
           k,
           r_type,
           r1,
           r_min,
           r_max,
           sd_env,
           phi,
           int_type,
           alpha,
           model,
           seed)

# empirical data

## raw data
source(here::here("code/data_fmt_fishdata.R"))
source(here::here("code/data_fmt_analysis.R"))

df_area <- d0 %>% 
  group_by(site_id, year) %>% 
  summarize(area = unique(area))

filename <- list.files(path = here::here("result"), full.names = T) %>% 
  as_tibble() %>% 
  filter(str_detect(string = .$value, pattern = "reg")) %>% 
  filter(!str_detect(string = .$value, pattern = "reg_rich")) %>% 
  pull()

df_beta <- lapply(filename, function(x) {
  read_csv(here::here(x)) %>% 
    filter(parameter == "b[2]")
})
names(df_beta) <- str_extract(filename, "all|masu|other")  

## ssm estimate
df_bp <- list.files(path = here::here("data_fmt"), full.names = T) %>% 
  as_tibble() %>% 
  filter(str_detect(string = .$value, pattern = "ssm")) %>% 
  pull() %>% 
  lapply(function(x) {
    read_csv(x) %>% 
      filter(param == "bp_value") %>% 
      select(mean) %>% 
      mutate(group = str_extract(x, "all|masu|other"))
  }) %>% 
  bind_rows()

## mcmc sample size
df_mcmc_ssm <- list.files(path = here::here("data_fmt"), full.names = T) %>% 
  as_tibble() %>% 
  filter(str_detect(string = .$value, pattern = "ssm")) %>% 
  pull() %>% 
  lapply(function(x) {
    read_csv(x) %>% 
      select(n_total_mcmc,
             n_sample,
             n_thin,
             n_burn) %>% 
      distinct()
  }) %>% 
  bind_rows()

df_mcmc_reg <- list.files(path = here::here("result"), full.names = T) %>% 
  as_tibble() %>% 
  filter(str_detect(string = .$value, pattern = "reg_")) %>% 
  filter(!str_detect(string = .$value, pattern = "rich")) %>% 
  pull() %>% 
  lapply(function(x) {
    read_csv(x) %>% 
      select(n_total_mcmc,
             n_sample,
             n_thin,
             n_burn) %>% 
      distinct()
  }) %>% 
  bind_rows()

## stocking data
source(here::here("code/data_fmt_stock.R"))

df_stock_stage <- df_stock %>% 
  group_by(release_stage) %>% 
  summarize(stock = sum(abundance)) %>% 
  mutate(ratio = stock / max(stock),
         prop = stock / sum(stock))

```

**Authors:** Akira Terui^1,\*^, Hirokazu Urabe^2^, Masayuki Senzaki^3^, Bungo Nishizawa^4^

\*Corresponding author: hanabi0111\@gmail.com

**Affiliations:** ^1^ Department of Biology, University of North Carolina at Greensboro, Greensboro, NC 27412, USA ^2^ Salmon and Freshwater Fisheries Research Institute, Hokkaido Research Organization, Eniwa, Hokkaido, 061-1433, Japan ^3^ Faculty of Environmental Earth Science, Hokkaido University, Sapporo, Hokkaido, 060-0810, Japan ^4^ National Institute of Polar Research, Tachikawa, Tokyo, 190-8518, Japan

# Abstract

The past decades have witnessed efforts to unveil ecological risks associated with massive releases of captive-bred individuals ("stock enhancement") [@arakiHatcheryStockingHelp2010; @krkosekDecliningWildSalmon2007]. Yet, this method is still pervasive in conservation and natural resource management, assuming that the demographic benefits exceed the associated risks [@kitadaEconomicEcologicalGenetic2018; @laikreCompromisingGeneticDiversity2010]. Here, contrary to this intuition, we show that stock enhancement undermines community stability with no demographic benefit to the enhanced species. Our theory predicted that stock enhancement destabilizes community dynamics by facilitating competitive exclusion while suppressing the natural recruitment of the enhanced species via intensified competition. Consistent with this prediction, stream fish communities showed greater temporal fluctuations and fewer species richness in rivers with the intensive stocking of hatchery masu salmon - a major freshwater resource in Japan [@kitadaLessonsJapanMarine2020]. The current overreliance on stock enhancement may accelerate global biodiversity loss, threatening the provisioning of ecosystem services. A radical change in management strategies is therefore required to achieve the sustainability of natural resources.

# Maintext

Human demands for natural resources are ever-increasing, such that active interventions are critical to the sustainable management of fisheries, forestry, and wildlife [@laikreCompromisingGeneticDiversity2010]. Captive breeding is a form of the efforts to enhance wild populations of diverse plant and animal taxa [@snyderLimitationsCaptiveBreeding1996; @laikreCompromisingGeneticDiversity2010]. Although releases of captive-bred organisms ("stock enhancement") entail ecological risks such as the accumulation of deleterious alleles [@arakiGeneticEffectsCaptive2007; @krkosekDecliningWildSalmon2007], this method is still pervasive in conservation [@snyderLimitationsCaptiveBreeding1996] and natural resource management [@laikreCompromisingGeneticDiversity2010]. In fisheries, for example, billions of hatchery individuals are released annually across the globe [@kitadaEconomicEcologicalGenetic2018]. The widespread use of captive breeding is perhaps because of the "myth" that the demographic benefits of released individuals may exceed the associated risks.

Current debates, however, overlook the fact that we have rarely assessed the community-wide impact of stock enhancement. Species are all embedded in the complex web of interacting organisms, and the stable coexistence of competing species through density-dependent feedback underpins the emergent stability of ecological communities [@tilmanEcologicalConsequencesChanges1999; @carrollNicheFitnessDifferences2011a; @loreauDoesFunctionalRedundancy2004]. Stock enhancement may disrupt the sensitive balance of species interactions because it introduces unnaturally high numbers of individuals into the wild [@careyNativeInvadersChallenges2012]. Hence, this form of species management may intervene in the ecological process that allows competing species to coexist, ultimately degrading the long-term community stability. Evidence for this hypothesis is lacking, however.

Here, we show that stock enhancement undermines long-term community stability, which we define as the relative size of fluctuations in total community density over time [@tilmanEcologicalConsequencesChanges1999]. Our theory illuminates that stock enhancement compromises the stabilizing mechanism emerging from species niche differences. The present study further demonstrates the relevance of this general theory to natural systems by showing its congruence with Japanese stream fish communities, where \~10 million hatchery masu salmon (*Oncorhynchus masou masou*) are released annually for fisheries, recreation, and conservation purposes [@kitadaLessonsJapanMarine2020].

We employed a multispecies Ricker model [@fowlerSpeciesDynamicsAlter2012] to simulate community dynamics with the selective stock enhancement of a constituent species (species 1). Specifically, the population density of species $i$ at time $t+1$, $N_{i,t+1}$, is modeled as:

$$
N_{i,t+1} = (N_{i,t}+\phi_i R_t)~exp\left[r_i\left(1-\frac{N_{i,t}+\alpha_{i1} R_t + \sum_{j=1}^S \alpha_{ij}N_{j,t}}{K_i}\right)\right]~exp(\epsilon_{i,t})
$$

where $r_i$ is the intrinsic growth rate, $\alpha_{ij}$ the competition coefficient of species $j$ on species $i$, $K_i$ the carrying capacity, $R_t$ the number of released individuals for the enhancement of species 1, and $\epsilon_{i,t}$ the species response to stochastic environmental fluctuations that follow a normal distribution $Normal(0,\sigma_{\epsilon}^2)$. To capture variation in species traits, intrinsic growth rates of unenhanced species and interspecific competition coefficients were drawn randomly from a uniform ($r_{i,i \ne 1} \sim Unif(0.5,2)$) and an exponential distribution ($\alpha_{ij,i \ne j} \sim Exp(1/\bar{\alpha})$). The parameter $\phi_i$ controls the relative fitness of captive-bred individuals as follows:

$$
\phi_i = \left\{
\begin{array}{cc}
f_R & (i = 1)\\
0 & (i \ne 1)
\end{array}
\right.
$$

$f_R~(\ge 0)$ is the density-independent survival of captive-bred individuals relative to wild individuals. Therefore, the model accounts for the fitness difference of captive-bred individuals due to genetic effects and/or plasticity [@weberInteractionsHatcheryWild2003; @snyderLimitationsCaptiveBreeding1996; @arakiHatcheryStockingHelp2010] when considering the reproductive contribution to the next generation. Without loss of generality, we assumed constant $K_i$ ($K_i = K$) and $R_t$ ($R_t = R$) across species and time, respectively.

We ran `r n_sim` time steps of `r max(sim_result$n_rep)` independent communities (i.e., simulation replicates) under each of `r nrow(param_set)` simulation scenarios. These scenarios cover a range of ecological contexts, differing in the intrinsic growth of an enhanced species $r_1$, competition $\bar{\alpha}$, carrying capacity $K$, and relative fitness $f_R$ (see **Methods**). Using the last `r unique(sim_result$n_timestep)` time steps, we obtained the following summary statistics of the total community density $\sum_i^SN_i$ to examine the community-level response to stock enhancement: coefficient of variation (CV), number of species persist (defined as $N_i > 0.01$ at $t=1600$), temporal mean ($\mu$), and temporal SD ($\sigma$). We also calculated the temporal mean and SD for the enhanced ($N_1$) and unenhanced species ($\sum_{i,i \ne 1}^S N_i$) separately to infer underlying mechanisms.

When carrying capacity was small ($K=100$), our model predicted a destabilizing effect of stock enhancement on ecological communities as illustrated by increased CV with increasing numbers of releases (**Figure 1A**). This pattern stemmed mainly from the reduced mean of the total community density, and both enhanced and unenhanced species groups were responsible (**Figure 1A**). The enhanced species decreased because stocking induced the negative competitive effect exceeding the reproductive contribution of released individuals [@satakeStockingCaptivebredFish2012]. Meanwhile, interspecific competition reduced the unenhanced species at high levels of stock enhancement, resulting in fewer persisting species (**Figure 1A**). Combined, the total community density decreased more sharply than individual species groups (**Figure 1A**). The SDs showed a similar trend, but the relationship was flatter at the community level (**Figure 1A**). Since a CV is a ratio of an SD to a mean, the steeper decline of the mean community density led to the increased CV. These patterns were qualitatively similar across most ecological contexts (robust to the changes in $r_1$, $\bar{\alpha}$, and $f_R$; **Figures S1-S3**).

The destabilizing effect emerges because stock enhancement affects the balance of species interactions that underpins community stability. In theory, the stable coexistence requires a niche difference that is large enough to overcome the relative difference in intrinsic competitive ability [@carrollNicheFitnessDifferences2011a]. Under this condition, competing species can grow from small populations because dominant species undergo stronger intraspecific competition [@carrollNicheFitnessDifferences2011a]. Such coexistence favors stable temporal dynamics of species-rich communities [@tilmanEcologicalConsequencesChanges1999] because it gives rise to "overyielding" [@loreauDoesFunctionalRedundancy2004; @carrollNicheFitnessDifferences2011a], i.e., total community density of a multispecies community exceeds what would be expected in a single species community ($\sum_i^S N_i > K$). However, stock enhancement is externally controlled, and the number of releases is not subject to density-dependent regulation. Therefore, released individuals impose additional intra- and interspecific competition that interferes with the ecological process producing overyielding.

Stock enhancement, however, had little influence on community dynamics when carrying capacity was sufficiently large ($K=500$; **Figures S4-S6**). In particular, stock enhancement increased the enhanced species with a low population growth rate ($r_1=0.5$; **Figure S4**). This result may explain why some of the best evidence for successful stock enhancement comes from long-lived endangered species [e.g., @jonesRestorationMauritiusKestrel1995]. More importantly, the contrasting community response at different carrying capacities provides deeper insights. One of the core motivations for stock enhancement is to mitigate declining trends of natural resources due to human impacts, such as habitat loss [@chaseEcosystemDecayExacerbates2020]. Ironically, our results suggest that stock enhancement will not bring desired outcomes unless we resolve root causes that compromise environmental capacity first.

To demonstrate the relevance of our general theory to natural systems, we assessed the potential impacts of the stock enhancement of masu salmon (**Figure 1E**) on the long-term stability of stream fish communities in Hokkaido, Japan. In the protected watersheds (all separated by the ocean; **Figure 1C, D**), a long-term program exists to monitor stream fish communities along with the official stocking records. The majority of stocking occurs in spring, after which salmon fry stay in freshwater for growing seasons. Therefore, the study system sets the stage for a "natural experiment" to test our theoretical predictions. We used the data from 1999 to 2019 at `r n_distinct(df_fish$site_id)` sites within `r n_distinct(df_fish$river)` independent watersheds (see **Methods** for selection criteria). Using hierarchical Bayesian models, we quantified the effect of stock enhancement on community dynamics while accounting for potential effects of climates and local abiotic factors.

As predicted, stream fish communities showed greater temporal fluctuations (higher CV) in watersheds with intensive stocking (**Figure 1B**). The effect was striking in its magnitude, almost doubling the CV at the highest stocking level. Our analysis strongly supported the positive relationship between the CV and the number of releases (**Figure 2**), in which the probability of the regression coefficient being positive was `r op(df_beta$all$prob_positive[df_beta$all$response == "cv"])` (**Table S8**). This pattern was associated with the reduced long-term average of the total community density and fewer species richness (**Figures 1B and 2**), and both enhanced (masu salmon) and unenhanced fish groups contributed to this trend (**Figures 1B and 2;** see **Tables S8-S10** for full statistics). In the meantime, the SDs had vague relationships with stock enhancement (**Figures 1B and 2**).

Competition is a likely mechanism, as our theory assumes. Hatchery salmons are larger and more aggressive than wild individuals, increasing the likelihood of intense intra- and interspecific competition in the wild [@weberInteractionsHatcheryWild2003]. Indeed, field and experimental studies confirmed that hatchery masu salmon competed with wild masu salmon and other stream fishes during their freshwater life stage, typically one year [@hasegawaWildMasuSalmon2018; @sahashiEvaluationContributionHatchery2015; @hasegawaPulsedSuppliesSmall2022]. Importantly, socioeconomic factors control the number of releases (e.g., budget allocation) regardless of the current condition of recipient communities. As such, released fish are probably "excessive" and may cause resource competition that would otherwise not exist.

The reduced fitness of hatchery masu salmon may also play a role in the observed response. Like other salmonids, ocean-migrating adults of hatchery masu salmon show lower return rates to the spawning river [@sahashiWildGenesBoostinpress]. In addition, the aggressive behavior of hatchery salmons may make them vulnerable to predation [@weberInteractionsHatcheryWild2003]. The fitness disadvantage may add to negative density dependence to influence community stability.

We cannot exclude the possibility that spurious correlations drove our results. However, the protected watersheds preserve nearly intact landscapes (**Figure S10**) with strict regulations of human activities (e.g., exploitation, construction of in-stream structures); therefore, it is difficult to envision that unmeasured human influences caused the observed relationships. Further, we have statistically controlled natural variation in environmental factors (see **Methods** and **Tables S8-S10**). This unique setup may have helped uncover the qualitative agreement between theory and empirical patterns.

Despite the significant attention to the fate of captive-bred individuals [@arakiHatcheryStockingHelp2010; @snyderLimitationsCaptiveBreeding1996], current schemes rarely consider the self-regulation process of biodiversity. Our results suggest that the ignorance of this critical process may erode the long-term persistence of the recipient community, likely impacting the provisioning of ecosystem services [@cardinaleBiodiversityLossIts2012]. While our empirical example is limited to stream fish communities, we anticipate that this phenomenon is pervasive in nature because the destabilizing effect emerged across diverse simulated scenarios.

We should prioritize habitat conservation with a broader scope of ecosystem management. Such efforts are particularly important in the Anthropocene because habitat degradation may exacerbate the undesired influence of stock enhancement. Protected areas and environmental restoration are promising tools to conserve biodiversity, and a smart spatial design is a key to achieving successful conservation. For example, coordinated placement of conservation sites considering spatial biodiversity patterns is crucial in improving the ecological outcomes [@teruiEmergentDualScaling2021; @koningNetworkGrassrootsReserves2020; @fontouraProtectingConnectivityPromotes2022]. Governance may also play a central role in enforcing environmental legislation, potentially determining the effectiveness of conservation investment [@amanoSuccessfulConservationGlobal2018]. These considerable potentials indicate that viable management options exist before blindly accepting stock enhancement. Without a comprehensive framework that appreciates the ecological integrity of natural communities, the stock enhancement will never be effective but impairs biodiversity.

# Methods

## Theory

We employed a multispecies Ricker model [@fowlerSpeciesDynamicsAlter2012]. In the basic formula without stock enhancement, the population density of species $i$ at time $t+1$, $N_{i,t+1}$, is modeled as:

```{=tex}
\begin{align}
N_{i,t+1} = N_{i,t}~exp\left[r_i \left(1-\frac{N_{i,t} + \sum_{j=1}^S \alpha_{ij}N_{j,t}}{K_i} \right) \right]exp(\epsilon_{i,t})
\end{align}
```
where $r_i$ is the intrinsic growth rate, $\alpha_{ij}$ the competition coefficient of species $j$ on $i$, $K_i$ the carrying capacity, and $\epsilon_{i,t}$ the species response to stochastic environmental fluctuations that obey an normal distribution $Normal(0, \sigma_{\epsilon}^2)$. We modified this formula to include the effects of stock enhancement (species 1) on reproduction and competition as follows:

```{=tex}
\begin{align}
N_{i,t+1} = (N_{i,t}+\phi_i R_t)~exp \left[r_i \left\{1-\frac{N_{i,t}+\alpha_{i1} (N_{1,t} + R_t) + \sum_{j=2}^S \alpha_{ij}N_{j,t}}{K_i} \right\} \right]exp(\epsilon_{i,t})
\end{align}
```
$R_t$ is the number of released individuals, and the parameter $\phi_i$ controls the relative fitness of captive-bred individuals:

```{=tex}
\begin{align}
\phi_i = 
\left\{
\begin{array}{cc}
f_R & (i = 1)\\
0 & (i \ne 1)
\end{array}
\right.
\end{align}
```
$f_R~(\ge 0)$ is the density-independent survival of captive-bred individuals relative to wild individuals. Equation (2) can be reorganized to:

```{=tex}
\begin{align}
N_{i,t+1} = (N_{i,t}+\phi_i R_t)~exp \left[r_i \left(1-\frac{N_{i,t}+\alpha_{i1}R_t + \sum_{j=1}^S \alpha_{ij}N_{j,t}}{K_i} \right) \right]exp(\epsilon_{i,t})
\end{align}
```
In this model, intrinsic growth rates of unenhanced species $r_{i,i \ne 1}$ and interspecific competition $\alpha_{ij}$ are random draws from a uniform ($r_{i,i \ne 1} \sim Unif(0.5,r_{max})$) and an exponential distribution ($\alpha_{ij} \sim Exp(1/\bar{\alpha})$), respectively. We assumed constant values of intraspecific competition ($\alpha_{ii}=1$), carrying capacity $(K_i = K)$ and the number of releases $(R_t=R)$.

Prior to the main simulation, we performed an extensive sensitivity analysis to identify parameters that strongly influence the relationship between community dynamics and stock enhancement (see **Supplementary text**). We identified five influential parameters (**Table S2-S4**), of which different values were considered in the main simulation as follows: intrinsic growth of enhanced species ($r_1 =$ `r unique(param_set$r1)`), average strength of interspecific competition ($\bar{\alpha}=$ `r unique(param_set$alpha)`), carrying capacity ($K=$ `r unique(param_set$k)`), and relative fitness of captive-bred individuals ($f_R=$ `r unique(param_set$phi)`). Meanwhile, we fixed values of the following parameters: the number of species ($S=$ `r unique(param_set$n_species)`), maximum intrinsic growth rate of unenhanced species ($r_{max}=$ `r unique(param_set$r_max)`), and environmental stochasticity ($\sigma_{\epsilon}=$ `r unique(param_set$sd_env)`). This simulation setup resulted in `r nrow(param_set)` sets of parameter combinations that cover a range of ecological scenarios.

Under each parameter combination, we ran `r n_sim` time steps of `r max(sim_result$n_rep)` independent communities (i.e., simulation replicates). The number of released individuals $R$ was drawn randomly from a uniform distribution for each simulation replicate as $R \sim Unif(0,500)$. We initialized the community with populations of each species drawn from a Poisson distribution with a mean of five. We repeated the seeding procedure every 10 time steps over the first `r unique(sim_result$n_warmup)` time steps to allow species to establish populations and reach equilibrium without stock enhancement (initialization period). After the initialization period, we released $R$ individuals of the enhanced species every time step over the next `r unique(sim_result$n_burnin)` time steps to reach new equilibrium with selective stock enhancement (burn-in period). We continued the simulation run with stock enhancement and saved the last `r unique(sim_result$n_timestep)` time steps. We obtained the following summary statistics of the whole community $\sum_i^SN_j$: the coefficient of variation (CV), the number of species persist (defied as $N_i > 0.01$ at $t=1600$), the temporal mean ($\mu$), and the SD ($\sigma$). The temporal mean and SD were also calculated for the enhanced species ($N_1$) and unenhanced species ($\sum_{i,i \ne 1}^S N_i$) separately. We summarized values of simulation parameters in **Table S1**.

## Empirical analysis

### Data

**Time-series data.** We assembled time-series fish data at `r n_distinct(d0$site_id)` sites within `r n_distinct(d0$river)` protected watersheds of Hokkaido Island, Japan. The Hokkaido Research Organization leads a long-term monitoring program at these watersheds, and the data are published as annual reports [@salmonandfreshwaterfisheriesresearchinstitutehokkaidoresearchorganizationAnnualReportMonitoring2021]. The program began in 1963, but an effective, standardized sampling method has been implemented since 1999 (two-pass sampling with a combination of electrofishing and cast net). Most data were collected in summer with irregular interannual intervals (1- to 3-year intervals for most cases), and sampling efforts were quantified by sampling area (average: `r op(mean(df_area$area))` $\pm$ `r op(sd(df_area$area))` m^2^). We confined our analysis to the sites that meet the following criteria: (i) the observation span (from the first to the last year of observation) exceeds 10 years, (ii) the number of observation years exceeds five years, and (iii) masu salmon is observed at least twice during the observation period. As a result, we used time-series data at `r n_distinct(df_fish$site_id)` sites within `r n_distinct(df_fish$river)` watersheds from 1999 to 2019. Summed abundance of first and second passes was used in the following analysis. **Table S5** summarizes observed species in these watersheds.

**Fish stocking.** The stocking of masu salmon began in the 1950s. Hatchery fish are released in spring (fry and smolt stages) and fall (juvenile stage). Although the fish release occurs at multiple locations within a watershed, the stocking information is available only at the watershed level. For each release stage, we assembled annual records of stock enhancement (the number of fish released; 1999-2019) from annual investigations by the Japan Fisheries Research and Education Agency and Salmon and Freshwater Fisheries Research Institute. During the study period, the majority of stocking took place in spring at a fry stage (fry : juvenile : smolt = `r pull(df_stock_stage, ratio)[1]` : `r op(pull(df_stock_stage, ratio)[2])` : `r op(pull(df_stock_stage, ratio)[3])`)

**Environmental data.** At each sampling site, we measured the following environmental variables as potential covariates: upstream watershed area (km^2^; a proxy for stream size), proportional land use in the upstream watershed (forest, urban, agriculture), local climates (annual mean air temperature [$^\circ C$] and cumulative precipitation [mm]), and ocean productivity (sea surface chlorophyll *a* concentration [mg m^-3^]). We used MERIT Hydro [@yamazakiMERITHydroHighresolution2019] to delineate the upstream watershed polygon for each sampling site. We estimated the proportion of forest, urban, and agriculture in each watershed polygon based on land use data in 2015 from Copernicus Global Land Service (100-m resolution) [@marcelbuchhornCopernicusGlobalLand2020]. Climate data at each sampling site were extracted from CHELSA version 1.2 [@kargerClimatologiesHighResolution2017; @kargerDataClimatologiesHigh2018]. We extracted annual data of chlorophyll *a* concentration (2002-2019; resolution, 4.6 km^2^) from OceanColor [@seawifsmissionpageNasaOceanBiology2019] as a proxy for ocean productivity and calculated the average value within the 30-km radius of each river mouth. We used the following R packages to perform geospatial analysis: *sf* [@pebesmaSimpleFeaturesStandardized2018]*, raster* [@hijmansRasterGeographicData2020]*, exactextractr* [@bastonExactextractrFastExtraction2020]*, stars* [@pebesmaStarsSpatiotemporalArrays2020]*, whitebox* [@lindsayWhiteboxGATCase2016]*.*

### Statistical analysis

Our goal is to compare temporal community dynamics across sites. However, the data are not comparable because of observation errors (e.g., different observers) and missing observations. To confront this challenge, we developed a Bayesian state-space model for three species groups separately: (i) whole community, the summed abundance of all species, (ii) enhanced species, the abundance of masu salmon, (iii) unenhanced species, the summed abundance of all species except masu salmon. A Bayesian state-space model is best suited for our analysis because it can account for observation errors while imputing missing values given the long-term trend at each site [@clarkPopulationTimeSeries2004; @keryBayesianPopulationAnalysis2012]. The model is composed of observation and state models, as described below.

In the observation model, we model observation processes. Fish abundance of either whole community, enhanced species (masu salmon), or unenhanced species at site $s$ in year $t$, $N_{s,t}$, was assumed to follow a Poisson distribution:

```{=tex}
\begin{align}
N_{s,t} \sim Poisson(\lambda_{s,t} A_{s,t})
\end{align}
```
where $\lambda_{s,t}$ is the expected fish density (individual m^-2^) and $A_{s,t}$ the sampling area (m^2^). Since fish sampling was conducted after the spring stocking of masu salmon, captured fish may include individuals released in the observation year. We explicitly modeled this observation process to avoid biases in estimating temporal community trends:

```{=tex}
\begin{align}
\lambda_{s,t} = n_{s,t}exp(\epsilon_{s,t}^{obs}) + \psi \beta_s~Fry_{w(s),t}
\end{align}
```
$n_{s,t}$ is the "true" fish density excluding fish released in the spring, $Fry_{w(s),t}$ the number of salmon fry released (unit: million fish) in spring in watershed $w$ within which site $s$ is located, and $\beta_s$ the site-specific effect of released salmon fry on the observed fish density. The parameter $\beta_s$ was drawn from a normal distribution with the hyper-mean $\mu_{\beta}$ and hyper-variance $\sigma_{\beta}^2$. The parameter $\epsilon_{s,t}^{obs}$ is the error term that follows a normal distribution $Normal(0, \sigma_{obs,s}^2)$. The inclusion of this term allows the model to account for site- and year-specific observation errors, which can be caused by ecological and/or artificial factors. When modeling the unenhanced species group, $\psi$ equals zero (otherwise $\psi = 1$) so the model excludes the term $\beta_s~Fry_{w(s),t}$.

In the state model, we model temporal dynamics of fish density $n_{s,t}$ as follows:

```{=tex}
\begin{align}
ln~n_{s,t+1} = ln~r_{s} + ln~n_{s,t} + \epsilon_{s,t}^{state}
\end{align}
```
where $ln~r_{s}$ is the site-specific rate of change at site $s$, and $\epsilon_{s,t}^{state}$ is the process error that follows a normal distribution as $\epsilon_{s,t}^{state} \sim Normal(0, \sigma_{state,s}^2)$. The site-specific rate of change is random draws from a normal distribution $ln~r_s \sim Normal(\mu_r, \sigma_r^2)$, assuming that community dynamics across Hokkaido have a shared temporal trend to some degree (the degree of shared trend is controlled by the SD $\sigma_r$). This hierarchical structure allows for improved parameter estimates by partially sharing information across sites [@gelmanDataAnalysisUsing2007]. We used median estimates of fish density $n_{s,t}$ to calculate the temporal CV, mean ($\mu$), and SD ($\sigma$) for each site. We summarized the reconstructed community dynamics in **Figures S7-S9**.

We assessed the predictive performance of our model using the Bayesian p-value [@keryIntroductionWinBUGSEcologists2010], a value of which takes a range of 0-1 and indicates over- (\~0.0), under- (\~1.0), or suitable-fitting (\~0.5) to the data. Bayesian p-values for our state-space models ranged from `r op(min(df_bp$mean))` to `r op(max(df_bp$mean))`, indicating that our model specification is appropriate.

We used linear regression to quantify the impact of stock enhancement on community dynamics. Although our focus is stock enhancement, each model included climatic and local abiotic variables to account for important environmental differences among sites. Specifically, we developed the following linear regression model taking either the CV, species richness (the number of species present during the observation period), mean, or SD as a response variable $y_s$ with a normal or a Poisson distribution.

```{=tex}
\begin{align}
\left\{
\begin{aligned}
ln~y_s &\sim Normal(\mu_{y,s}, \sigma_y^2) &&\text{for CV, mean, and SD}\\
y_s &\sim Poisson(\lambda_{y,s} exp(\epsilon_{\lambda,s})) &&\text{for species richness}
\end{aligned}
\right.
\end{align}
```
where $\sigma_y$ is the SD of residual errors and $exp(\epsilon_{\lambda,s})$ is the error term that accounts for overdispersion ($\epsilon_{\lambda,s} \sim Normal(0, \sigma_{\lambda}^2)$). The expected means were related to linear predictors as follows:

```{=tex}
\begin{align}
\left\{
\begin{aligned}
\mu_{y,s} &= \gamma_{0,w(s)} + \sum_k \gamma_kx_{k,s} &&\text{for CV, mean, and SD}\\
ln~\lambda_{y,s} &= \gamma_{0,w(s)} + \sum_k \gamma_kx_{k,s} &&\text{for species richness}
\end{aligned}
\right.
\end{align}
```
$\gamma_{0,w(s)}$ is the watershed-specific intercept ($w(s)$ refers to site $s$ nested within watershed $w$) and $\gamma_k (k > 0)$ are the regression coefficients of site-level predictors $x_k$. The site-level predictors include upstream watershed area (log-transformed), air temperature, precipitation, and forest land use. Urban and agricultural land use were omitted because of either a limited value range (**Figure S10**) or a strong correlation with forest land use (**Figure S11**). The watershed-specific intercept was related to watershed-level predictors as:

```{=tex}
\begin{align}
\gamma_{0,w} &\sim Normal(\mu_{\gamma,w},\sigma_{\gamma}^2)\\
\mu_{\gamma,w} &=\delta_0+\sum_k\delta_k z_{k,w}
\end{align}
```
$\delta_{0}$ is the global intercept and $\delta_k (k > 0)$ are the regression coefficients. The watershed-level predictors $z_{k,w}$ include the yearly stocking of masu salmon (fry + juvenile + smolt; averaged for1999-2019) and ocean productivity (chlorophyll *a* concentration; averaged for 2002-2019). Ocean productivity was included because the majority of the observed species use marine habitats at a certain life stage (i.e., diadromous). The parameter $\sigma_{\gamma}$ accounts for random variation among watersheds that the watershed-level predictors cannot capture. All predictors were standardized (mean = 0, SD = 1) before the analysis.

We fitted the models to the data using JAGS version 4.1.0 through *runjags* package version 2.2.0-2 in R [@denwoodRunjagsPackageProviding2016]. We assigned weakly informative priors to parameters (**Table S6**). Three Markov chain Monte Carlo (MCMC) chains were run until parameter estimates converged. Total MCMC interations ranged from `r min(df_mcmc_ssm$n_total_mcmc)` to `r max(df_mcmc_ssm$n_total_mcmc)` for the state-space models and was `r unique(df_mcmc_reg$n_total_mcmc)` for the regression models. The first `r unique(c(df_mcmc_ssm$n_burn, df_mcmc_reg$n_burn))` iterations were discarded as burn-in, and MCMC samples were saved every `r unique(df_mcmc_ssm$n_thin)` (state-space) and `r unique(df_mcmc_reg$n_thin)` iterations (regression) to reduce autocorrelation. Convergence was assessed by examining whether the $\hat{R}$ indicator of each parameter approached \< 1.1 [@gelmanDataAnalysisUsing2007]. Data manipulation and analysis were performed in R version 4.1.0 [@rcoreteamLanguageEnvironmentStatistical2021]. Parameter estimates were summarized in **Table S7-S10**.

# Acknowledgments

We are grateful to people involved in the long-term monitoring program at the protected watersheds in Hokkaido. We thank Genki Sahashi and Masato Yamamichi for helpful discussion on this manuscript.

# Funding

No funding.

# Author contributions

AT conceived the project. AT, HU and BN assembled data for empirical analysis. AT analyzed data with inputs from HU, MS, and BN. AT wrote the first draft and HU, MS, and BN significantly contributed to the final version of the manuscript.

# Competing interests

None declared.

# **Data and materials availability**

Data and codes are available at <https://github.com/aterui/public-proj_fishery-stability>.

# References
