pacman::p_load(tidyverse,
               patchwork,
               here,
               cdyns,
               foreach,
               doParallel,
               doSNOW,
               scales,
               runjags)
